name: Rust

on:
  pull_request:
    branches: [master, main]
  merge_group:
  push:
    branches: [master, main]

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.rs
            contracts/Cargo.lock
      - name: Build
        if: env.GIT_DIFF
        run: cargo build --verbose
      - name: Clippy
        if: env.GIT_DIFF
        run: cargo clippy
      - name: Run tests
        if: env.GIT_DIFF
        run: cargo test --verbose
